#IDIOMAS DOMINADOS
#DESCRIPCION
#Muestra un catálogo del personal ordenado por idiomas
#FIN_DESCRIPCION
SELECT P.CLAVE, P.NOMBREN || " " || NOMBREP || " " || NOMBREM AS NOMBRE, 
               I. IDIOMA, C.DESCRIPCION, I.ESCRITO, I.LEIDO, I.HABLADO
FROM EMPPRIN P, EMPIDIOM I, IDIOMA C
WHERE  I.IDIOMA = :CLAVE_IDIOMA AND
               P.CLAVE = I.CLAVE AND
               I.IDIOMA = C.CLAVE
ORDER BY I.IDIOMA
