SELECT P.CLAVE, P.ID, P.CLAVE_CONCEPTO, P.MONTO, P. DESCUENTO, P.SALDO, A.TIPO,
SUM(A. MONTO) AS ABONO
FROM EMPPRES P LEFT JOIN EMPABO A ON A.PRESTAMO = P.ID,
           EMPPRIN E
WHERE P.FECHA <= "02/28/2001" AND P.SALDO > 0 AND E.CLAVE = P.CLAVE AND E. TIPO_NOM = "QCNA"
      AND P.ESTADO="S"
GROUP BY P.CLAVE, P.ID, P.CLAVE_CONCEPTO, P.MONTO, P. DESCUENTO, P.SALDO, A.TIPO
HAVING A.FECHA >= "02/16/2001" AND A.FECHA <= "02/28/2001" AND A.TIPO=0
